### ISSUE TITLE
 Package devscast/maxicash has requirements incompatible with your PHP version, PHP extensions and Composer version.

### ISSUE THREAD

**Issue by bolenge** [devscast/maxicash#1]
Hi, I appreciate this package. I would like to use it, but there is an issue with compatibility with other PHP versions. I think, given that it is still in its early versions, it would be better if it is compatible even with PHP 7 versions so that it can be used in older PHP projects.

Error message on installation :

  _Package devscast/maxicash has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - devscast/maxicash 1.0.1 requires php >=8.2 which does not match your installed version 8.1.13._

**Comment by bernard-ng** [comment]
Hello @bolenge 

Unfortunately, I won't be adding support for a PHP version that's already at the end of its life, but you can clone the project and add support in your case. 

![image](https://github.com/devscast/maxicash/assets/31113941/3d7880f9-b87a-4aaf-bbe5-1f3788c6d8df)

https://www.php.net/supported-versions.php
